version: "3"
services:
  telegraf:
    image: telegraf
    restart: always
    ports:
      - "998:998"
    container_name: "telegraf"
    networks:
      - "monitoring"
    environment:
      - "HOST_PROC=/host/proc"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/proc:/host/proc:ro"
      - "/etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
  influxdb:
    image: "influxdb:1.8"
    restart: always
    container_name: "influxdb"
    ports:
      - "8086:8086"
    networks:
      - "monitoring"
    volumes:
      - "influxdb:/var/lib/influxdb"
  grafana:
    image: "grafana/grafana"
    restart: always
    container_name: "grafana"
    ports:
      - "3000:3000"
    networks:
      - "monitoring"
    volumes:
      - "grafana-storage:/var/lib/grafana"

networks:
  monitoring:
    name: "monitoring"
    external: true

volumes:
  influxdb:
    name: "influxdb"
    external: true
  grafana-storage:
    name: "grafana-storage"
    external: true
